// =============================================================================
// Inventory catalogue — 12 demonstration units. DUMMY DATA for a placeholder
// showroom: prices, mileage and stock are illustrative only (see /compliance).
//
// Structure vs. text: hard facts (price, specs, images) live here; all prose
// (descriptions, feature names) lives in i18n keyed by the car `slug` under
// `cars.<slug>.*`. Keep both locales in lockstep when adding a car.
//
// Images are local, licence-free photos under /public/cars (downloaded via
// `pnpm cars`). Swap them for real showroom photography before going live.
// =============================================================================
import type { Car } from '~/types'

export const inventory: readonly Car[] = [
  {
    slug: 'mercedes-amg-gt-2023',
    make: 'Mercedes-AMG',
    model: 'GT Coupé',
    year: 2023,
    priceIdr: 4_850_000_000,
    condition: 'used',
    bodyType: 'coupe',
    fuel: 'petrol',
    transmission: 'automatic',
    mileageKm: 8_200,
    horsepower: 523,
    acceleration: 3.9,
    seats: 2,
    colorKey: 'colors.graphiteGrey',
    image: '/cars/01-mercedes-amg-gt.jpg',
    gallery: ['/cars/01-mercedes-amg-gt.jpg', '/cars/05-bmw-m4.jpg', '/cars/10-bmw-m5.jpg'],
    featureKeys: ['f.amgPerformance', 'f.carbonTrim', 'f.burmesterAudio', 'f.ceramicBrakes'],
    featured: true,
  },
  {
    slug: 'porsche-911-carrera-2024',
    make: 'Porsche',
    model: '911 Carrera S',
    year: 2024,
    priceIdr: 3_450_000_000,
    condition: 'new',
    bodyType: 'sport',
    fuel: 'petrol',
    transmission: 'automatic',
    mileageKm: 0,
    horsepower: 473,
    acceleration: 3.5,
    seats: 4,
    colorKey: 'colors.lavaOrange',
    image: '/cars/02-porsche-911.jpg',
    gallery: ['/cars/02-porsche-911.jpg', '/cars/07-porsche-718.jpg', '/cars/04-lamborghini-huracan.jpg'],
    featureKeys: ['f.sportChrono', 'f.pasm', 'f.sportExhaust', 'f.matrixLed'],
    featured: true,
  },
  {
    slug: 'lamborghini-huracan-2022',
    make: 'Lamborghini',
    model: 'Huracán EVO',
    year: 2022,
    priceIdr: 8_900_000_000,
    condition: 'used',
    bodyType: 'sport',
    fuel: 'petrol',
    transmission: 'automatic',
    mileageKm: 4_500,
    horsepower: 631,
    acceleration: 2.9,
    seats: 2,
    colorKey: 'colors.arancioBorealis',
    image: '/cars/04-lamborghini-huracan.jpg',
    gallery: ['/cars/04-lamborghini-huracan.jpg', '/cars/02-porsche-911.jpg', '/cars/03-chevrolet-camaro.jpg'],
    featureKeys: ['f.v10Engine', 'f.awd', 'f.ldvi', 'f.forgedWheels'],
    featured: true,
  },
  {
    slug: 'bmw-m4-competition-2023',
    make: 'BMW',
    model: 'M4 Competition',
    year: 2023,
    priceIdr: 2_650_000_000,
    condition: 'used',
    bodyType: 'coupe',
    fuel: 'petrol',
    transmission: 'automatic',
    mileageKm: 12_400,
    horsepower: 503,
    acceleration: 3.9,
    seats: 4,
    colorKey: 'colors.alpineWhite',
    image: '/cars/05-bmw-m4.jpg',
    gallery: ['/cars/05-bmw-m4.jpg', '/cars/10-bmw-m5.jpg', '/cars/01-mercedes-amg-gt.jpg'],
    featureKeys: ['f.mxDrive', 'f.carbonRoof', 'f.harmanKardon', 'f.laserLights'],
    featured: true,
  },
  {
    slug: 'mercedes-s-class-2024',
    make: 'Mercedes-Benz',
    model: 'S 500 L',
    year: 2024,
    priceIdr: 3_150_000_000,
    condition: 'new',
    bodyType: 'sedan',
    fuel: 'hybrid',
    transmission: 'automatic',
    mileageKm: 0,
    horsepower: 429,
    acceleration: 4.9,
    seats: 5,
    colorKey: 'colors.obsidianBlack',
    image: '/cars/06-mercedes-s-class.jpg',
    gallery: ['/cars/06-mercedes-s-class.jpg', '/cars/11-audi-rs7.jpg', '/cars/08-mercedes-g-class.jpg'],
    featureKeys: ['f.rearLounge', 'f.mbux', 'f.airmatic', 'f.burmester4d'],
    featured: true,
  },
  {
    slug: 'porsche-718-cayman-2023',
    make: 'Porsche',
    model: '718 Cayman GTS',
    year: 2023,
    priceIdr: 2_250_000_000,
    condition: 'used',
    bodyType: 'coupe',
    fuel: 'petrol',
    transmission: 'manual',
    mileageKm: 15_800,
    horsepower: 394,
    acceleration: 4.5,
    seats: 2,
    colorKey: 'colors.racingYellow',
    image: '/cars/07-porsche-718.jpg',
    gallery: ['/cars/07-porsche-718.jpg', '/cars/02-porsche-911.jpg', '/cars/09-tesla-model-s.jpg'],
    featureKeys: ['f.flatSix', 'f.sportChrono', 'f.bose', 'f.sportSeatsPlus'],
  },
  {
    slug: 'mercedes-g-class-2023',
    make: 'Mercedes-Benz',
    model: 'G 63 AMG',
    year: 2023,
    priceIdr: 6_450_000_000,
    condition: 'used',
    bodyType: 'suv',
    fuel: 'petrol',
    transmission: 'automatic',
    mileageKm: 9_600,
    horsepower: 585,
    acceleration: 4.5,
    seats: 5,
    colorKey: 'colors.obsidianBlack',
    image: '/cars/08-mercedes-g-class.jpg',
    gallery: ['/cars/08-mercedes-g-class.jpg', '/cars/12-range-rover.jpg', '/cars/06-mercedes-s-class.jpg'],
    featureKeys: ['f.v8Biturbo', 'f.threeDiffLocks', 'f.nappaLeather', 'f.adaptiveDamping'],
    featured: true,
  },
  {
    slug: 'tesla-model-s-plaid-2024',
    make: 'Tesla',
    model: 'Model S Plaid',
    year: 2024,
    priceIdr: 2_950_000_000,
    condition: 'new',
    bodyType: 'sedan',
    fuel: 'electric',
    transmission: 'automatic',
    mileageKm: 0,
    horsepower: 1020,
    acceleration: 2.1,
    seats: 5,
    colorKey: 'colors.pearlWhite',
    image: '/cars/09-tesla-model-s.jpg',
    gallery: ['/cars/09-tesla-model-s.jpg', '/cars/06-mercedes-s-class.jpg', '/cars/11-audi-rs7.jpg'],
    featureKeys: ['f.triMotor', 'f.longRange', 'f.autopilot', 'f.glassRoof'],
    featured: true,
  },
  {
    slug: 'bmw-m5-2022',
    make: 'BMW',
    model: 'M5 Competition',
    year: 2022,
    priceIdr: 2_150_000_000,
    condition: 'used',
    bodyType: 'sedan',
    fuel: 'petrol',
    transmission: 'automatic',
    mileageKm: 21_300,
    horsepower: 617,
    acceleration: 3.3,
    seats: 5,
    colorKey: 'colors.marinaBlue',
    image: '/cars/10-bmw-m5.jpg',
    gallery: ['/cars/10-bmw-m5.jpg', '/cars/05-bmw-m4.jpg', '/cars/01-mercedes-amg-gt.jpg'],
    featureKeys: ['f.mxDrive', 'f.merinoLeather', 'f.harmanKardon', 'f.headUpDisplay'],
  },
  {
    slug: 'audi-rs7-sportback-2023',
    make: 'Audi',
    model: 'RS7 Sportback',
    year: 2023,
    priceIdr: 3_050_000_000,
    condition: 'used',
    bodyType: 'sedan',
    fuel: 'hybrid',
    transmission: 'automatic',
    mileageKm: 11_100,
    horsepower: 591,
    acceleration: 3.6,
    seats: 5,
    colorKey: 'colors.daytonaGrey',
    image: '/cars/11-audi-rs7.jpg',
    gallery: ['/cars/11-audi-rs7.jpg', '/cars/06-mercedes-s-class.jpg', '/cars/09-tesla-model-s.jpg'],
    featureKeys: ['f.quattro', 'f.bangOlufsen', 'f.matrixLed', 'f.airSuspension'],
  },
  {
    slug: 'range-rover-autobiography-2024',
    make: 'Land Rover',
    model: 'Range Rover Autobiography',
    year: 2024,
    priceIdr: 5_650_000_000,
    condition: 'new',
    bodyType: 'suv',
    fuel: 'hybrid',
    transmission: 'automatic',
    mileageKm: 0,
    horsepower: 523,
    acceleration: 4.6,
    seats: 5,
    colorKey: 'colors.santoriniBlack',
    image: '/cars/12-range-rover.jpg',
    gallery: ['/cars/12-range-rover.jpg', '/cars/08-mercedes-g-class.jpg', '/cars/06-mercedes-s-class.jpg'],
    featureKeys: ['f.terrainResponse', 'f.meridianAudio', 'f.executiveSeats', 'f.cabinAirPurification'],
    featured: true,
  },
  {
    slug: 'chevrolet-camaro-ss-2021',
    make: 'Chevrolet',
    model: 'Camaro SS',
    year: 2021,
    priceIdr: 1_450_000_000,
    condition: 'used',
    bodyType: 'coupe',
    fuel: 'petrol',
    transmission: 'manual',
    mileageKm: 28_700,
    horsepower: 453,
    acceleration: 4.0,
    seats: 4,
    colorKey: 'colors.rallyRed',
    image: '/cars/03-chevrolet-camaro.jpg',
    gallery: ['/cars/03-chevrolet-camaro.jpg', '/cars/04-lamborghini-huracan.jpg', '/cars/02-porsche-911.jpg'],
    featureKeys: ['f.v8Ls', 'f.magneticRide', 'f.brembo', 'f.dualExhaust'],
  },
] as const
