// =============================================================================
// Localized per-page SEO helper. Accepts refs/getters so title & description
// stay reactive to the active locale. Centralizes brand suffix + OG/Twitter and
// lets a page override the share image (e.g. a car photo on a detail page).
//
// Rich link previews (WhatsApp, Instagram, Facebook, Twitter/X) are built from
// Open Graph tags, so we emit an ABSOLUTE og:image URL plus og:image:width/
// height/type and og:image:alt — WhatsApp in particular needs an absolute,
// reachable https image to render a card.
// =============================================================================
import { brandConfig } from '~/config/brand.config'

type Source = MaybeRefOrGetter<string>

interface PageSeoOptions {
  /** Absolute or root-relative OG/Twitter image path. */
  image?: MaybeRefOrGetter<string | undefined>
  /** OG type; defaults to 'website'. */
  type?: 'website' | 'article' | 'product'
}

// All share images are a uniform 1200×630 (the default og-image.png and the
// per-car crops under /cars/social generated by `pnpm og`), so we can always
// declare these dimensions — WhatsApp/Instagram/Facebook read them for the card.
const DEFAULT_OG = { path: '/og-image.png', width: 1200, height: 630 }

export const usePageSeo = (
  title: Source,
  description: Source,
  options: PageSeoOptions = {},
) => {
  const site = useSiteConfig()
  const route = useRoute()
  const fullTitle = () => `${toValue(title)} · ${brandConfig.name}`

  const toAbsolute = (path: string) =>
    path.startsWith('http') ? path : `${site.url}${path.startsWith('/') ? '' : '/'}${path}`

  const image = () => {
    const override = toValue(options.image)
    return toAbsolute(override || DEFAULT_OG.path)
  }
  const imageType = () =>
    /\.png($|\?)/i.test(image()) ? 'image/png' : 'image/jpeg'
  const canonical = () => toAbsolute(route.path)

  useSeoMeta({
    title: () => toValue(title),
    ogTitle: fullTitle,
    twitterTitle: fullTitle,
    description: () => toValue(description),
    ogDescription: () => toValue(description),
    twitterDescription: () => toValue(description),
    ogType: options.type ?? 'website',
    ogSiteName: brandConfig.name,
    ogUrl: canonical,
    ogImage: image,
    ogImageSecureUrl: image,
    ogImageType: imageType,
    ogImageAlt: fullTitle,
    ogImageWidth: DEFAULT_OG.width,
    ogImageHeight: DEFAULT_OG.height,
    twitterImage: image,
    twitterImageType: imageType,
    twitterImageAlt: fullTitle,
    twitterCard: 'summary_large_image',
  })
}
